apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  LOCATION: "remote"

  # Logger config
  LOGGER_LEVEL: "debug"
  LOGGER_ENCODING: "console"
  LOGGER_LEVEL_ENCODER: "lower"

  # Database config
  DB_DSN: "postgres://auth-service:auth-service@auth-pg:5002/auth-service?sslmode=disable"

  # Redis config
  REDIS_SENTINEL_ADDRESSES: "redis-service:6379"
  REDIS_PASSWORD: "auth-service"
