output   = "authservicedb"
pkgname  = "authservicedb"
wipe     = true
no-tests = false
add-enum-types = true

[psql]
  host    = "localhost"
  port    = 5002
  dbname  = "auth-service"
  schema  = "public"
  user    = "auth-service"
  pass    = "auth-service"
  sslmode = "disable"
  blacklist = ["schema_migrations"]

[[types]]
  [types.match]
  type = "int"
  [types.replace]
  type = "int64"
