apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyf-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyf-service
  template:
    metadata:
      labels:
        app: hyf-service
    spec:
      containers:
        - name: hyf-service
          image: holod8/hyf-service
          envFrom:
            - configMapRef:
                name: hyf-service-config
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hyf-service
spec:
  selector:
    app: hyf-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
