apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyf-pg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: "hyf"
            - name: POSTGRES_USER
              value: "hyf"
            - name: POSTGRES_PASSWORD
              value: "hyf"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: hyf-pg
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
