version: '3'

dotenv: [ '.env' ]

vars:
  DATABASE_USER: hyf
  DATABASE_DSN: postgres://hyf:hyf@todo_db:5432/hyf?sslmode=disable

tasks:
  run-dev:
    aliases: [ run ]
    desc: runs (app, database, migration) locally with dev credentials.
    cmds:
      - docker-compose -f docker-compose.override.yaml -f ../var/docker/docker-compose.yaml up -d
    env:
      LOCATION: remote
      LOGGER_LEVEL: debug
      LOGGER_ENCODING: console
      LOGGER_LEVEL_ENCODER: lower
      DB_DSN: postgres://hyf:hyf@todo_db:5432/hyf?sslmode=disable

  ent-gen:
    desc: generate entities
    cmds:
      - sqlboiler psql --no-tests -d -o pkg/gen/sqlboiler/hyfdb -c sqlboiler.toml

  buf-format:
    desc: format *.proto files.
    cmds:
      - buf format -w

  buf-gen:
    desc: generates artifacts from *.proto files.
    cmds:
      - buf generate
    generates:
      - "pkg/gen/hyf"

  buf-mod-update:
    desc: generates artifacts from *.proto files.
    cmds:
      - buf dep update ./api/proto
    generates:
      - "pkg/gen/hyf"

  run-tests:
    desc: run tests ( firstly authorize ).
    cmds:
      - go clean -testcache && go test -v ./__tests__/auth_api_test.go
      - go clean -testcache && go test -v ./__tests__/todo_api_test.go
    generates:
      - "pkg/gen/hyf"

  build:
    desc: build werf image.
    cmds:
      - werf build --dev
